name: Release Helm Chart

on:
  push:
    tags:
      - "chart-v*"

jobs:
  package-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      HELM_EXPERIMENTAL_OCI: 1
      CHART_DIR: helm/myapp
      REGISTRY: ghcr.io
      REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4
      - name: Login to GHCR (OCI)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Package chart
        run: |
          version=$(grep '^version:' ${CHART_DIR}/Chart.yaml | awk '{print $2}')
          helm package ${CHART_DIR} --version ${version}
          echo "CHART_PKG=myapp-${version}.tgz" >> $GITHUB_ENV
      - name: Push to GHCR (OCI)
        run: |
          helm push ${CHART_PKG} oci://ghcr.io/${REPO}
